### ISSUE TITLE
Images in the README are broken and not showing up

### ISSUE THREAD

**Issue by VisualDevelopment** [Discord-RP/Visual-Studio#12]
**Bug description:**

When you visit the homepage of the repository or the Visual Studio Marketplace, the image links are dead!

**Reproduction steps:**

1. Go to the homepage of the repository or the Visual Studio Marketplace,
2. Notice the image links are dead.

**Expected behavior:**

The image links show up, but they are dead.

**Screenshots:**

![image](https://user-images.githubusercontent.com/30368284/86664758-ad16c780-bff7-11ea-9448-835101925e6e.png)
![image](https://user-images.githubusercontent.com/30368284/86664807-b7d15c80-bff7-11ea-9b58-25c9da8487e5.png)

**Desktop (please complete the following information):**

 - OS: Windows 10 2004 Build 19041.329
 - Browser: Firefox 78.0.1

**Additional context:**

The image CDN is dead

**Comment by SebiTalent04** [comment]
Same here

**Comment by kotx** [comment]
You may need to reupload the images to the repository or another image host. If your host is owo.whats-th.is (guessing from the domain sorry-there-is.nothing-to-see-he.re), you might want to switch off of it for long term storage.

**Comment by VisualDevelopment** [comment]
I know how to fix this, I just don't have a Windows VM to work on the extension.
