### ISSUE TITLE
VB.NET unrecognized extension

### ISSUE THREAD

**Issue by Virenbar** [Discord-RP/Visual-Studio#18]
**Bug description:**

Discord is showing icon for an unrecognized extension when editing *.vb files.

**Reproduction steps:**

1. Open any *.vb file.
2. Start editing.
3. Check profile status in discord.

**Expected behavior:**

Show VB icon when editing *.vb file.

**Screenshots:**

![image](https://user-images.githubusercontent.com/10138491/90335114-b8dcad00-dfeb-11ea-8566-6c15dd4c3a72.png)

**Desktop:**

 - OS: Windows 10 1909 Build 18363.1016
 - Visual Studio: Community 2019 Version 16.7.1
 - Extension Version: 5.3

**Comment by VisualDevelopment** [comment]
Not a bug, it's just not implemented, please change your issue to a feature request.
