### ISSUE TITLE
Idling status does not update

### ISSUE THREAD

**Issue by ANF-Studios** [Discord-RP/Visual-Studio#19]
**Bug description:**
The idling status does not update when closing all files

**Reproduction steps:**
Open VS 2019 with all the files closed in your project, you will get idling status. However, if you open a file and then close all of them, you won't get that same stuff. You would rather get the status of the last file you closed.
![image](https://user-images.githubusercontent.com/68814933/92664218-d2d48b80-f31c-11ea-8ec4-6df91895efdd.png)

**Desktop (please complete the following information):**

 - OS: Windows 10 1909 
 - Visual Studio 2019
 - v5.3

**Additional context**
Well nothing more, if you need more info you can ask me.

**Comment by VisualDevelopment** [comment]
Hi, thanks for reporting an issue.
This issue is known, and a fix is being discussed.
