### ISSUE TITLE
Translate for RU 

### ISSUE THREAD

**Issue by 1thenikita** [Discord-RP/Visual-Studio#21]
**Problem:**

I'm upset that this plugin doesn't have a translation in my language.

**Solution:**

How can I help with translation in my language?

**Comment by VisualDevelopment** [comment]
Hi, if you want translations you must setup a system so it can use different strings for the text for me

**Comment by 1thenikita** [comment]
> Привет, если вы хотите переводы, вы должны настроить систему так, чтобы она могла использовать разные строки в тексте для меня

Do you plan to put the translation for English and my language in a separate class?

**Comment by VisualDevelopment** [comment]
I will look into a more official and easy way of translations when I start working on the extension again

**Comment by 1thenikita** [comment]
> I will look into a more official and easy way of translations when I start working on the extension again

When will this happen?

**Comment by VisualDevelopment** [comment]
We've been discussing internally some stuff and we're thinking of a C++ rewrite soon, so probably when we start the rewrite

**Comment by 1thenikita** [comment]
> We've been discussing internally some stuff and we're thinking of a C++ rewrite soon, so probably when we start the rewrite

Let me ask you, what are the advantages or what will be the reason for switching to C++?

**Comment by VisualDevelopment** [comment]
Performance mostly, I'm also more comfortable with it

**Comment by 1thenikita** [comment]
I added translation support to the plugin, and I'll upload a Pull Request in a few days, okay?

**Comment by 1thenikita** [comment]
I started it, I hope that the merger will happen)

**Comment by 1thenikita** [comment]
@VisualDevelopment are you here?
