### ISSUE TITLE
Rich Presence doesn't update when the first active window at load is not a document

### ISSUE THREAD

**Issue by BluTree** [Discord-RP/Visual-Studio#4]
**Describe the bug**
The rich presence doesn't update when visual studio opens the solution and the first window is not a document

**To Reproduce**
1. Open a project
2. Close every document windows
3. Restart the project

**Expected behavior**
The rich presence should update at start, even if no document is opened

**Comment by VisualDevelopment** [comment]
Noted. Will be fixed in a new release!
